[build-system]
requires = [
    "flit_core >=3.2,<4"
]
build-backend = "flit_core.buildapi"

[project]
authors = [
    {name = "James Hodgkinson", email = "james@terminaloutcomes.com"}
]
classifiers = [
    "License :: OSI Approved :: MIT License"
]
dynamic = [
    "version",
    "description"
]

dependencies = [
    "click >=8.0.1",
    "telethon >=1.24.0",
]

keywords = [
    "download",
    "telegram",
    "images",
    "image",
    "jpeg",
    "jpg"
]
name = "telegrab"
readme = "README.md"

[project.optional-dependencies]
dev = [
    "pytest",
    "mypy",
    "flit"
]

[project.urls]
Home = "https://github.com/yaleman/telegrab"

[project.scripts]
fuckjpeg = "telegrab.__main__:cli"


[tool.flit.sdist]
exclude = [
    "requirements*.txt",
    ".gitignore",
    "config.py",
    ".pylintrc",
    "*.session",
    "*.session-journal",
    "downloads/",
    "venv/",
    ".github/",
]
