[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "telegrab"
version = "0.0.6"
description = "A tool for downloading files from Telegram."
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

keywords = [
    "download",
    "telegram",
    "images",
    "image",
    "jpeg",
    "jpg"
]

[tool.poetry.dependencies]
python = "^3.9"
Telethon = "^1.24.0"
click = "^8.0.4"
questionary = "^1.10.0"
pydantic = "^1.9.0"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
pytest = "^7.1.1"
black = "^22.1.0"
mypy = "^0.941"
pylint-pydantic = "^0.1.4"

[project.scripts]
telegrab = "telegrab.__main__:cli"
[tool.poetry.scripts]
telegrab = "telegrab.__main__:cli"