name: Run pylint

"on":
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Running tests
        run: |
            uv sync --frozen --group dev
            uv run pylint $(basename $(pwd))
            uv run pylint test*.py
