name: Run pytest

"on":
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Running pytest
        run: |
          uv sync --frozen --group dev
          uv run python -m pytest
